# Generated by Django 6.1 on 2026-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='user_key',
            field=models.CharField(db_index=True, default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
