# Generated by Django 6.1 on 2026-08-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
