# Generated by Django 6.1 on 2026-08-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_alter_schema_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
